import { branchKind, jumpTarget, nextPc } from "./ir";
import type { DecodedInstruction, DecodedProto } from "./types";

export interface BasicBlock { id:number; start:number; end:number; instructions:DecodedInstruction[]; succs:number[]; preds:number[]; }
export interface CFG { blocks:BasicBlock[]; blockByStart:Map<number,number>; blockOf:(pc:number)=>number; entry:number; idom:number[]; domFrontier:Set<number>[]; postIdom:number[]; reachable:Set<number>; loops:NaturalLoop[]; }
export interface NaturalLoop { header:number; latches:number[]; body:Set<number>; }

function findLeaders(proto:DecodedProto):Set<number>{const leaders=new Set<number>();if(proto.instructions.length===0)return leaders;leaders.add(0);for(const ins of proto.instructions){const kind=branchKind(ins);if(kind==="none")continue;if(kind==="fastcall-guard"){const t=jumpTarget(ins);if(t!==null)leaders.add(t);continue;}const t=jumpTarget(ins);if(t!==null)leaders.add(t);if(kind!=="return")leaders.add(nextPc(ins));}return leaders;}

export function buildCFG(proto:DecodedProto):CFG{
 const instructions=proto.instructions,leaders=findLeaders(proto),sortedLeaders=[...leaders].filter((l)=>l>=0&&l<=instructions.length).sort((a,b)=>a-b),blocks:BasicBlock[]=[],blockByStart=new Map<number,number>(),pcToInsIndex=new Map<number,number>();instructions.forEach((ins,idx)=>pcToInsIndex.set(ins.pc,idx));
 for(let i=0;i<sortedLeaders.length;i++){const start=sortedLeaders[i],end=i+1<sortedLeaders.length?sortedLeaders[i+1]:(instructions.length?nextPc(instructions[instructions.length-1]):0),startIdx=pcToInsIndex.get(start);if(startIdx===undefined)continue;const blockIns:DecodedInstruction[]=[];for(const ins of instructions.slice(startIdx)){if(ins.pc>=end)break;blockIns.push(ins);}const id=blocks.length;blocks.push({id,start,end,instructions:blockIns,succs:[],preds:[]});blockByStart.set(start,id);}
 const blockOf=(pc:number):number=>{let lo=0,hi=blocks.length-1;while(lo<=hi){const mid=(lo+hi)>>1,b=blocks[mid];if(pc<b.start)hi=mid-1;else if(pc>=b.end)lo=mid+1;else return b.id;}return-1;};
 for(const b of blocks){if(b.instructions.length===0)continue;const last=b.instructions[b.instructions.length-1],kind=branchKind(last),addEdge=(targetPc:number)=>{const t=blockOf(targetPc);if(t>=0&&!b.succs.includes(t))b.succs.push(t);};switch(kind){case"return":break;case"jump":case"fastcall-guard":{const t=jumpTarget(last);if(t!==null)addEdge(t);break;}case"cond2":case"fornprep":case"forgprep":case"fornloop":case"forgloop":{const t=jumpTarget(last);if(t!==null)addEdge(t);addEdge(nextPc(last));break;}default:addEdge(b.end);}}
 for(const b of blocks)for(const s of b.succs)if(!blocks[s].preds.includes(b.id))blocks[s].preds.push(b.id);
 const entry=0,reachable=computeReachable(blocks,entry),idom=computeDominators(blocks,entry,reachable),domFrontier=computeDominanceFrontiers(blocks,idom,reachable),postIdom=computePostDominators(blocks,reachable),loops=findNaturalLoops(blocks,idom,reachable);return{blocks,blockByStart,blockOf,entry,idom,domFrontier,postIdom,reachable,loops};
}
function computeReachable(blocks:BasicBlock[],entry:number):Set<number>{const seen=new Set<number>();if(blocks.length===0)return seen;const stack=[entry];while(stack.length){const b=stack.pop()!;if(seen.has(b))continue;seen.add(b);for(const s of blocks[b].succs)if(!seen.has(s))stack.push(s);}return seen;}
function computeDominators(blocks:BasicBlock[],entry:number,reachable:Set<number>):number[]{const idom=new Array(blocks.length).fill(-1);if(blocks.length===0)return idom;const order=reversePostorder(blocks,entry,reachable),rpoIndex=new Map<number,number>();order.forEach((b,i)=>rpoIndex.set(b,i));idom[entry]=entry;let changed=true,guard=0;while(changed&&guard++<100000){changed=false;for(const b of order){if(b===entry)continue;const preds=blocks[b].preds.filter((p)=>reachable.has(p)&&idom[p]!==-1);if(preds.length===0)continue;let newIdom=preds[0];for(const p of preds.slice(1))newIdom=intersect(newIdom,p,idom,rpoIndex);if(idom[b]!==newIdom){idom[b]=newIdom;changed=true;}}}return idom;}
function intersect(a:number,b:number,idom:number[],rpoIndex:Map<number,number>):number{let i1=a,i2=b;const idx=(x:number)=>rpoIndex.get(x)??-1;let guard=0;while(i1!==i2&&guard++<100000){while(idx(i1)>idx(i2))i1=idom[i1];while(idx(i2)>idx(i1))i2=idom[i2];}return i1;}
function reversePostorder(blocks:BasicBlock[],entry:number,reachable:Set<number>):number[]{const visited=new Set<number>(),post:number[]=[],stack:Array<{id:number;i:number}>=[{id:entry,i:0}];visited.add(entry);while(stack.length){const top=stack[stack.length-1],succs=blocks[top.id].succs;if(top.i<succs.length){const next=succs[top.i++];if(reachable.has(next)&&!visited.has(next)){visited.add(next);stack.push({id:next,i:0});}}else{post.push(top.id);stack.pop();}}return post.reverse();}
function computeDominanceFrontiers(blocks:BasicBlock[],idom:number[],reachable:Set<number>):Set<number>[]{const df:Set<number>[]=blocks.map(()=>new Set());for(const b of blocks){if(!reachable.has(b.id)||b.preds.length<2)continue;for(const p of b.preds){if(!reachable.has(p))continue;let runner=p;while(runner!==idom[b.id]&&runner!==-1){df[runner].add(b.id);if(runner===idom[runner])break;runner=idom[runner];}}}return df;}
function computePostDominators(blocks:BasicBlock[],reachable:Set<number>):number[]{const postIdom=new Array(blocks.length).fill(-1),exits=blocks.filter((b)=>reachable.has(b.id)&&b.succs.length===0).map((b)=>b.id);if(exits.length===0)return postIdom;const virtualExit=blocks.length,revPreds:number[][]=blocks.map((b)=>b.succs.slice()),revSuccs:number[][]=blocks.map((b)=>b.preds.slice());for(const e of exits)revSuccs[e]=[...revSuccs[e],virtualExit];const nodes=[...reachable,virtualExit],order:number[]=[],visited=new Set<number>(),stack:Array<{id:number;i:number}>=[{id:virtualExit,i:0}];visited.add(virtualExit);const succsOf=(n:number)=>n===virtualExit?exits:revSuccs[n]??[];while(stack.length){const top=stack[stack.length-1],succs=succsOf(top.id);if(top.i<succs.length){const nxt=succs[top.i++];if(nodes.includes(nxt)&&!visited.has(nxt)){visited.add(nxt);stack.push({id:nxt,i:0});}}else{order.push(top.id);stack.pop();}}const rpo=order.reverse(),rpoIndex=new Map<number,number>(),pidom=new Map<number,number>();rpo.forEach((b,i)=>rpoIndex.set(b,i));pidom.set(virtualExit,virtualExit);let changed=true,guard=0;while(changed&&guard++<100000){changed=false;for(const b of rpo){if(b===virtualExit)continue;const preds=(exits.includes(b)?[...revPreds[b],virtualExit]:revPreds[b]??[]).filter((p)=>pidom.has(p));if(preds.length===0)continue;let newIdom=preds[0];for(const p of preds.slice(1)){let i1=newIdom,i2=p;const idx=(x:number)=>rpoIndex.get(x)??-1;let g2=0;while(i1!==i2&&g2++<100000){while(idx(i1)>idx(i2))i1=pidom.get(i1)??virtualExit;while(idx(i2)>idx(i1))i2=pidom.get(i2)??virtualExit;}newIdom=i1;}if(pidom.get(b)!==newIdom){pidom.set(b,newIdom);changed=true;}}}for(const b of reachable)postIdom[b]=pidom.get(b)??-1;return postIdom;}
function findNaturalLoops(blocks:BasicBlock[],idom:number[],reachable:Set<number>):NaturalLoop[]{const loops:NaturalLoop[]=[],dominates=(a:number,b:number):boolean=>{let n=b,guard=0;while(n!==-1&&guard++<100000){if(n===a)return true;if(idom[n]===n)break;n=idom[n];}return false;},backEdgesByHeader=new Map<number,number[]>();for(const b of blocks){if(!reachable.has(b.id))continue;for(const s of b.succs)if(reachable.has(s)&&dominates(s,b.id)){const arr=backEdgesByHeader.get(s)??[];arr.push(b.id);backEdgesByHeader.set(s,arr);}}for(const [header,latches]of backEdgesByHeader){const body=new Set<number>([header]),stack=[...latches];while(stack.length){const n=stack.pop()!;if(body.has(n))continue;body.add(n);for(const p of blocks[n].preds)if(reachable.has(p)&&!body.has(p))stack.push(p);}loops.push({header,latches,body});}return loops;}
