import type { Confidence, ConstantValue, DecodedInstruction, DecodedProto } from "./types";

export interface NameCandidate { name:string; confidence:Confidence; evidence:string; }
const RESERVED=new Set(["and","break","do","else","elseif","end","false","for","function","if","in","local","nil","not","or","repeat","return","then","true","until","while","continue"]);
export function sanitizeIdentifier(raw:string):string { let s=raw.replace(/[^A-Za-z0-9_]/g,"_"); if(!/^[A-Za-z_]/.test(s)) s="_"+s; if(s.length===0)s="_"; if(RESERVED.has(s))s+="_"; return s; }
function lowerFirst(s:string):string { return s?s[0].toLowerCase()+s.slice(1):s; }
const SERVICE_HINTS:Record<string,string>={Players:"players",ReplicatedStorage:"replicatedStorage",ServerScriptService:"serverScriptService",ServerStorage:"serverStorage",Workspace:"workspace",Lighting:"lighting",TweenService:"tweenService",RunService:"runService",UserInputService:"userInputService",HttpService:"httpService",DataStoreService:"dataStoreService",SoundService:"soundService",CollectionService:"collectionService",ContextActionService:"contextActionService",StarterGui:"starterGui",StarterPack:"starterPack",StarterPlayer:"starterPlayer",MarketplaceService:"marketplaceService",Teams:"teams",Chat:"chat",PhysicsService:"physicsService",ProximityPromptService:"proximityPromptService",MessagingService:"messagingService"};
const PROPERTY_HINTS:Record<string,string>={LocalPlayer:"localPlayer",Character:"character",Humanoid:"humanoid",HumanoidRootPart:"humanoidRootPart",PrimaryPart:"primaryPart",Parent:"parent",Name:"name",Position:"position",CFrame:"cframe",Value:"value"};
const METHOD_RESULT_HINTS:Record<string,string>={GetService:"__service__",GetPlayers:"players",FindFirstChild:"child",WaitForChild:"child",GetChildren:"children",GetDescendants:"descendants",Clone:"clone",new:"instance"};
const CALLBACK_PARAM_HINTS:Record<string,string[]>={PlayerAdded:["player"],PlayerRemoving:["player"],Touched:["hit"],Heartbeat:["deltaTime"],RenderStepped:["deltaTime"],Stepped:["time","deltaTime"],ChildAdded:["child"],ChildRemoved:["child"],Changed:["property"]};
export interface RegisterEvidence { importPath?:string; namecallMethod?:string; namecallArgConstant?:string; gettableKey?:string; isLoopIndex?:boolean; isLoopValue?:boolean; isTableConstructor?:boolean; isParam?:number; isSelf?:boolean; isVarargCapture?:boolean; debugName?:string|null; callbackContext?:string; callbackParamIndex?:number; }
export function inferName(ev:RegisterEvidence,fallbackBase:string):NameCandidate {
 if(ev.debugName)return{name:sanitizeIdentifier(ev.debugName),confidence:"EXACT",evidence:"debug local/upvalue name"};
 if(ev.namecallArgConstant&&ev.namecallMethod==="GetService"){const hint=SERVICE_HINTS[ev.namecallArgConstant];if(hint)return{name:hint,confidence:"HIGH",evidence:`game:GetService("${ev.namecallArgConstant}")`};return{name:lowerFirst(sanitizeIdentifier(ev.namecallArgConstant)),confidence:"MEDIUM",evidence:`GetService("${ev.namecallArgConstant}") result`};}
 if(ev.importPath){const last=ev.importPath.split(".").pop()!;if(PROPERTY_HINTS[last])return{name:PROPERTY_HINTS[last],confidence:"HIGH",evidence:`import path ${ev.importPath}`};return{name:lowerFirst(sanitizeIdentifier(last)),confidence:"MEDIUM",evidence:`import path ${ev.importPath}`};}
 if(ev.gettableKey&&PROPERTY_HINTS[ev.gettableKey])return{name:PROPERTY_HINTS[ev.gettableKey],confidence:"HIGH",evidence:`.${ev.gettableKey} property access`};
 if(ev.namecallMethod&&METHOD_RESULT_HINTS[ev.namecallMethod]){const hint=METHOD_RESULT_HINTS[ev.namecallMethod];if(hint!=="__service__")return{name:hint,confidence:"MEDIUM",evidence:`:${ev.namecallMethod}(...) result`};}
 if(ev.gettableKey)return{name:lowerFirst(sanitizeIdentifier(ev.gettableKey)),confidence:"MEDIUM",evidence:`.${ev.gettableKey} property access`};
 if(ev.callbackContext&&CALLBACK_PARAM_HINTS[ev.callbackContext]){const names=CALLBACK_PARAM_HINTS[ev.callbackContext],idx=ev.callbackParamIndex??0;if(names[idx])return{name:names[idx],confidence:"HIGH",evidence:`${ev.callbackContext} callback parameter #${idx+1}`};}
 if(ev.isSelf)return{name:"self",confidence:"EXACT",evidence:"implicit self parameter (NAMECALL)"}; if(ev.isLoopIndex)return{name:"i",confidence:"LOW",evidence:"numeric for-loop index"}; if(ev.isLoopValue)return{name:"item",confidence:"LOW",evidence:"generic for-loop value"}; if(ev.isVarargCapture)return{name:"args",confidence:"LOW",evidence:"captured varargs"}; if(ev.isTableConstructor)return{name:"t",confidence:"LOW",evidence:"table constructor result"}; if(ev.isParam!==undefined)return{name:`param${ev.isParam+1}`,confidence:"FALLBACK",evidence:"function parameter"}; return{name:fallbackBase,confidence:"FALLBACK",evidence:"no naming evidence available"};
}
export function collectEvidence(proto:DecodedProto):Map<number,RegisterEvidence>{
 const ev=new Map<number,RegisterEvidence>(); const get=(r:number)=>{let e=ev.get(r);if(!e){e={};ev.set(r,e);}return e;}; for(let p=0;p<proto.numParams;p++)get(p).isParam=p;
 const constStr=(c:ConstantValue|undefined):string|undefined=>c&&c.tag==="string"?c.string:undefined; const instructions=proto.instructions;
 for(let idx=0;idx<instructions.length;idx++){const ins:DecodedInstruction=instructions[idx];switch(ins.opname){case"GETIMPORT":{const c=proto.constants[ins.D];if(c&&c.tag==="import"&&c.importPath)get(ins.A).importPath=c.importPath;break;}case"GETTABLEKS":{const key=ins.aux!==undefined?constStr(proto.constants[ins.aux]):undefined;if(key)get(ins.A).gettableKey=key;break;}case"NAMECALL":{const method=ins.aux!==undefined?constStr(proto.constants[ins.aux]):undefined;if(method){get(ins.A).namecallMethod=method;const next=instructions[idx+1];if(next&&next.opname==="LOADK"){const argc=proto.constants[next.D];if(argc&&argc.tag==="string")get(ins.A).namecallArgConstant=argc.string;}}break;}case"NEWTABLE":case"DUPTABLE":get(ins.A).isTableConstructor=true;break;case"GETVARARGS":get(ins.A).isVarargCapture=true;break;case"FORNPREP":get(ins.A+3<=254?ins.A+3:ins.A).isLoopIndex=true;break;case"FORGLOOP":get(ins.A+2<=254?ins.A+2:ins.A).isLoopValue=true;break;}}
 for(const local of proto.locals){const e=get(local.register);if(local.nameConstant)e.debugName=local.nameConstant;} return ev;
}
