import type { InstructionMode, OpcodeSpec } from "./types";

function op(id: number, name: string, mode: InstructionMode, hasAux: boolean, confidence: OpcodeSpec["confidence"], sinceVersion = 1, extra: Partial<OpcodeSpec> = {}): OpcodeSpec {
  return { id, name, mode, hasAux, confidence, sinceVersion, ...extra };
}

export const OPCODES: OpcodeSpec[] = [
  op(0,"NOP","ABC",false,"EXACT"), op(1,"BREAK","ABC",false,"EXACT"), op(2,"LOADNIL","ABC",false,"EXACT"), op(3,"LOADB","ABC",false,"EXACT"), op(4,"LOADN","AD",false,"EXACT"), op(5,"LOADK","AD",false,"EXACT"), op(6,"MOVE","ABC",false,"EXACT"), op(7,"GETGLOBAL","ABC",true,"EXACT"), op(8,"SETGLOBAL","ABC",true,"EXACT"), op(9,"GETUPVAL","ABC",false,"EXACT"), op(10,"SETUPVAL","ABC",false,"EXACT"), op(11,"CLOSEUPVALS","ABC",false,"EXACT"), op(12,"GETIMPORT","AD",true,"EXACT"),
  op(13,"GETTABLE","ABC",false,"HIGH"), op(14,"SETTABLE","ABC",false,"HIGH"), op(15,"GETTABLEKS","ABC",true,"HIGH"), op(16,"SETTABLEKS","ABC",true,"HIGH"), op(17,"GETTABLEN","ABC",false,"HIGH"), op(18,"SETTABLEN","ABC",false,"HIGH"), op(19,"NEWCLOSURE","AD",false,"HIGH"), op(20,"NAMECALL","ABC",true,"HIGH"), op(21,"CALL","ABC",false,"HIGH"), op(22,"RETURN","ABC",false,"HIGH"), op(23,"JUMP","AD",false,"HIGH"), op(24,"JUMPBACK","AD",false,"HIGH"), op(25,"JUMPIF","AD",false,"HIGH"), op(26,"JUMPIFNOT","AD",false,"HIGH"), op(27,"JUMPIFEQ","AD",true,"HIGH"), op(28,"JUMPIFLE","AD",true,"HIGH"), op(29,"JUMPIFLT","AD",true,"HIGH"), op(30,"JUMPIFNOTEQ","AD",true,"HIGH"), op(31,"JUMPIFNOTLE","AD",true,"HIGH"), op(32,"JUMPIFNOTLT","AD",true,"HIGH"), op(33,"ADD","ABC",false,"HIGH"), op(34,"SUB","ABC",false,"HIGH"), op(35,"MUL","ABC",false,"HIGH"), op(36,"DIV","ABC",false,"HIGH"), op(37,"MOD","ABC",false,"HIGH"), op(38,"POW","ABC",false,"HIGH"), op(39,"ADDK","ABC",false,"HIGH"), op(40,"SUBK","ABC",false,"HIGH"), op(41,"MULK","ABC",false,"HIGH"), op(42,"DIVK","ABC",false,"HIGH"), op(43,"MODK","ABC",false,"HIGH"), op(44,"POWK","ABC",false,"HIGH"), op(45,"AND","ABC",false,"HIGH"), op(46,"OR","ABC",false,"HIGH"), op(47,"ANDK","ABC",false,"HIGH"), op(48,"ORK","ABC",false,"HIGH"), op(49,"CONCAT","ABC",false,"HIGH"), op(50,"NOT","ABC",false,"HIGH"), op(51,"MINUS","ABC",false,"HIGH"), op(52,"LENGTH","ABC",false,"HIGH"), op(53,"NEWTABLE","ABC",true,"HIGH"), op(54,"DUPTABLE","AD",false,"HIGH"), op(55,"SETLIST","ABC",true,"HIGH"), op(56,"FORNPREP","AD",false,"HIGH"), op(57,"FORNLOOP","AD",false,"HIGH"), op(58,"FORGLOOP","AD",true,"HIGH",3), op(59,"DEP_FORGPREP_INEXT","AD",false,"HIGH",1,{removedInVersion:3,deprecated:true}), op(60,"DEP_FORGLOOP_INEXT","AD",true,"HIGH",1,{removedInVersion:3,deprecated:true}), op(61,"DEP_FORGPREP_NEXT","AD",false,"HIGH",1,{removedInVersion:3,deprecated:true}), op(62,"DEP_FORGLOOP_NEXT","AD",true,"HIGH",1,{removedInVersion:3,deprecated:true}), op(63,"GETVARARGS","ABC",false,"HIGH"), op(64,"DUPCLOSURE","AD",false,"HIGH"), op(65,"PREPVARARGS","ABC",false,"HIGH"), op(66,"LOADKX","ABC",true,"HIGH"), op(67,"JUMPX","E",false,"HIGH"), op(68,"FASTCALL","ABC",false,"HIGH"), op(69,"COVERAGE","E",false,"HIGH"), op(70,"CAPTURE","ABC",false,"HIGH"), op(71,"DEP_JUMPIFEQK","AD",true,"HIGH",1,{removedInVersion:3,deprecated:true}), op(72,"DEP_JUMPIFNOTEQK","AD",true,"HIGH",1,{removedInVersion:3,deprecated:true}), op(73,"FASTCALL1","ABC",false,"HIGH"), op(74,"FASTCALL2","ABC",true,"HIGH"), op(75,"FASTCALL2K","ABC",true,"HIGH"), op(76,"FORGPREP","AD",false,"HIGH",3), op(77,"JUMPXEQKNIL","AD",true,"HIGH",3), op(78,"JUMPXEQKB","AD",true,"HIGH",3), op(79,"JUMPXEQKN","AD",true,"HIGH",3), op(80,"JUMPXEQKS","AD",true,"HIGH",3), op(81,"IDIV","ABC",false,"HIGH",4), op(82,"IDIVK","ABC",false,"HIGH",4), op(83,"SUBRK","ABC",false,"HIGH",5), op(84,"DIVRK","ABC",false,"HIGH",5), op(85,"FASTCALL3","ABC",true,"HIGH",6),
];

export const OPCODE_BY_ID = new Map<number, OpcodeSpec>(OPCODES.map((o) => [o.id, o]));
export const OPCODE_BY_NAME = new Map<string, OpcodeSpec>(OPCODES.map((o) => [o.name, o]));
export const MAX_KNOWN_OPCODE = Math.max(...OPCODES.map((o) => o.id));

export const CONSTANT_TAG = { NIL:0, BOOLEAN:1, NUMBER:2, STRING:3, IMPORT:4, TABLE:5, CLOSURE:6, VECTOR:7 } as const;
export const CAPTURE_TYPE = ["VAL", "REF", "UPVAL"] as const;

export const BUILTIN_FUNCTIONS: Record<number,string> = {
1:"assert",2:"math.abs",3:"math.acos",4:"math.asin",5:"math.atan2",6:"math.atan",7:"math.ceil",8:"math.cosh",9:"math.cos",10:"math.deg",11:"math.exp",12:"math.floor",13:"math.fmod",14:"math.frexp",15:"math.ldexp",16:"math.log10",17:"math.log",18:"math.max",19:"math.min",20:"math.modf",21:"math.pow",22:"math.rad",23:"math.sinh",24:"math.sin",25:"math.sqrt",26:"math.tanh",27:"math.tan",28:"bit32.arshift",29:"bit32.band",30:"bit32.bnot",31:"bit32.bor",32:"bit32.bxor",33:"bit32.btest",34:"bit32.extract",35:"bit32.lrotate",36:"bit32.lshift",37:"bit32.replace",38:"bit32.rrotate",39:"bit32.rshift",40:"type",41:"string.byte",42:"string.char",43:"string.len",44:"typeof",45:"string.sub",46:"math.clamp",47:"math.sign",48:"math.round",49:"rawset",50:"rawget",51:"rawequal",52:"table.insert",53:"table.remove",54:"table.unpack",55:"vector",56:"bit32.countlz",57:"bit32.countrz",58:"select",59:"rawlen",60:"bit32.extractk",61:"table.getn",62:"table.setmetatable",63:"table.getmetatable",64:"table.tostring",65:"table.freeze",66:"table.isfrozen",67:"buffer.readi8",68:"buffer.readu8",69:"buffer.writeu8",70:"buffer.readi16",71:"buffer.readu16",72:"buffer.writeu16",73:"buffer.readi32",74:"buffer.readu32",75:"buffer.writeu32",76:"buffer.readf32",77:"buffer.writef32",78:"buffer.readf64",79:"buffer.writef64"};
