import type { CFG } from "./cfg";
import type { BlockExit, FunctionRecovery } from "./build";
import type { Expr, Stmt } from "./ast";
import type { Diagnostic } from "./types";

interface LoopCtx { bodyBlocks:Set<number>; exitBlock:number|null; continueBlock:number|null; parent:LoopCtx|null; }

export function structureFunction(cfg:CFG,recovery:FunctionRecovery,diagnostics:Diagnostic[],protoLabel:string):Stmt[]{
 const visited=new Set<number>(); const guardLimit=Math.max(2000,cfg.blocks.length*20); let guard=0;
 const stmtsOf=(id:number):Stmt[]=>recovery.blocks.get(id)?.stmts??[];
 const exitOf=(id:number):BlockExit=>recovery.blocks.get(id)?.exit??{kind:"fallthrough"};
 function isLoopHeaderStart(startBlock:number):{exit:number;kind:"fornum"|"forgen"}|null{for(const pred of cfg.blocks[startBlock]?.preds??[]){const ex=exitOf(pred);if((ex.kind==="fornum"||ex.kind==="forgen")&&cfg.blocks[pred].succs[1]===startBlock)return{exit:cfg.blocks[pred].succs[0],kind:ex.kind};}return null;}
 function findEnclosingLoopExit(target:number,loop:LoopCtx|null){let l=loop;while(l){if(l.continueBlock!==null&&target===l.continueBlock)return{isBreak:false,isContinue:true,loop:l};if(l.exitBlock!==null&&target===l.exitBlock&&!l.bodyBlocks.has(target))return{isBreak:true,isContinue:false,loop:l};l=l.parent;}return{isBreak:false,isContinue:false,loop:null};}
 function structureLinear(startBlock:number|null,stop:number|null,loop:LoopCtx|null):Stmt[]{const out:Stmt[]=[];let cur=startBlock;while(cur!==null&&cur!==stop){if(guard++>guardLimit){diagnostics.push({severity:"warning",stage:"structure",message:`${protoLabel}: structuring iteration limit reached; remaining control flow emitted as a flat comment fallback`});out.push({kind:"comment",text:"-- decompiler note: remaining control flow was too complex to structure within analysis limits"});break;}if(visited.has(cur)||!cfg.reachable.has(cur))break;const curId=cur;
  const forInfo=isLoopHeaderStart(curId);if(forInfo){const prepBlockId=cfg.blocks[curId].preds.find((p)=>{const ex=exitOf(p);return(ex.kind==="fornum"||ex.kind==="forgen")&&cfg.blocks[p].succs[1]===curId;})!;visited.add(prepBlockId);const prepExit=exitOf(prepBlockId) as Extract<BlockExit,{kind:"fornum"|"forgen"}>;const natLoop=cfg.loops.find((l)=>l.header===curId);const bodyBlocks=natLoop?natLoop.body:new Set([curId]);const latch=natLoop?natLoop.latches[0]:curId;const loopCtx:LoopCtx={bodyBlocks,exitBlock:forInfo.exit,continueBlock:latch,parent:loop};const preludeStmts=stmtsOf(prepBlockId);const innerBody=structureLinear(curId,latch,loopCtx);if(latch!==curId)for(const s of stmtsOf(latch))innerBody.push(s);out.push(...preludeStmts);if(prepExit.kind==="fornum")out.push({kind:"numericFor",varName:prepExit.varName,start:prepExit.startExpr,stop:prepExit.stopExpr,step:isDefaultStep(prepExit.stepExpr)?null:prepExit.stepExpr,body:innerBody});else out.push({kind:"genericFor",names:prepExit.names,exprs:prepExit.exprs,body:innerBody});cur=forInfo.exit;continue;}
  visited.add(curId);const block=cfg.blocks[curId],exit=exitOf(curId),blockStmts=stmtsOf(curId);
  if(exit.kind==="return"){out.push(...blockStmts,{kind:"return",values:exit.values});cur=null;continue;}
  if(exit.kind==="fallthrough"||exit.kind==="jump"){out.push(...blockStmts);const target=block.succs[0];if(target===undefined){cur=null;continue;}const je=findEnclosingLoopExit(target,loop);if(je.isBreak){out.push({kind:"break"});cur=null;}else if(je.isContinue){out.push({kind:"continue"});cur=null;}else cur=target;continue;}
  if(exit.kind==="cond"){out.push(...blockStmts);const takenTarget=block.succs[0],fallTarget=block.succs[1];const natLoop=cfg.loops.find((l)=>l.header===curId);if(natLoop&&!isLoopHeaderStart(curId)){const takenInLoop=natLoop.body.has(takenTarget),fallInLoop=natLoop.body.has(fallTarget);if(takenInLoop!==fallInLoop){const bodyEntry=takenInLoop?takenTarget:fallTarget,exitBlock=takenInLoop?fallTarget:takenTarget,cond:Expr=takenInLoop?exit.cond:{kind:"not",operand:exit.cond};const loopCtx:LoopCtx={bodyBlocks:natLoop.body,exitBlock,continueBlock:natLoop.header,parent:loop};const body=structureLinear(bodyEntry,curId,loopCtx);out.push({kind:"while",cond,body});cur=exitBlock;continue;}}
   const backEdgeLoop=cfg.loops.find((l)=>l.latches.includes(curId));if(backEdgeLoop&&(takenTarget===backEdgeLoop.header||fallTarget===backEdgeLoop.header)){const toHeader=takenTarget===backEdgeLoop.header,cond=toHeader?exit.cond:({kind:"not",operand:exit.cond} as Expr),exitBlock=toHeader?fallTarget:takenTarget;out.push({kind:"comment",text:"-- repeat/until condition"});out.push({kind:"if",branches:[{cond,body:[{kind:"break"}]}],elseBody:null});cur=exitBlock;continue;}
   const merge=cfg.postIdom[curId],thenStop=merge,je=loop?findEnclosingLoopExit(takenTarget,loop):{isBreak:false,isContinue:false,loop:null},jf=loop?findEnclosingLoopExit(fallTarget,loop):{isBreak:false,isContinue:false,loop:null};let thenBody:Stmt[],elseBody:Stmt[]|null;if(je.isBreak||je.isContinue)thenBody=[je.isBreak?{kind:"break"}:{kind:"continue"}];else thenBody=structureLinear(takenTarget,thenStop,loop);if(jf.isBreak||jf.isContinue)elseBody=[jf.isBreak?{kind:"break"}:{kind:"continue"}];else if(fallTarget===merge)elseBody=null;else elseBody=structureLinear(fallTarget,thenStop,loop);out.push({kind:"if",branches:[{cond:exit.cond,body:thenBody}],elseBody});cur=merge>=0&&merge<cfg.blocks.length?merge:null;continue;}
  out.push(...blockStmts);out.push({kind:"comment",text:`-- decompiler note: unrecognized loop control shape at block ${curId}`});cur=block.succs[0]??null;
 }return out;}
 function isDefaultStep(e:Expr){return e.kind==="number"&&e.value===1;}
 return structureLinear(cfg.entry,null,null);
}
